version: '3.3'
services:
  app:
    image: node:16.14-alpine
    tty: true
    stdin_open: true
    container_name: blog
    working_dir: /app
    depends_on:
      - db
    ports:
      - 3001:3001
    volumes:
      - ./:/app
  db:
    image: mysql:8.0.23
    container_name: blog-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password